name: Simplified Workflow Without Pre-Commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Calculer la version et le tag
      - name: Calculate version
        id: version
        run: |
          echo "Calculating version..."
          MAJOR_MINOR=$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*" || echo "v0.0")
          PATCH_VERSION=$(git log $(git describe --tags --abbrev=0 || echo "HEAD")..HEAD --oneline --first-parent | wc -l)
          VERSION="${MAJOR_MINOR}.${PATCH_VERSION}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Étape 3 : Afficher la version pour le débogage
      - name: Debug version
        run: |
          echo "Calculated version: ${{ steps.version.outputs.version }}"

      # Étape 4 : Linting (ou autre tâche légère)
      - name: Lint code
        run: echo "Running linting checks (placeholder)."
