name: Simplified Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job principal : vérifier le code et exécuter des étapes légères
  check-code:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clone tout l'historique Git

      # Étape 2 : Désactiver les hooks pre-commit (si besoin)
      - name: Skip pre-commit checks
        run: git config core.hooksPath /dev/null

      # Étape 3 : Calculer la version et le tag
      - name: Calculate version
        id: version
        run: |
          MAJOR_MINOR=$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*" || echo "v0.0")
          PATCH_VERSION=$(git log $(git describe --tags --abbrev=0 || echo "HEAD")..HEAD --oneline --first-parent | wc -l)
          VERSION="${MAJOR_MINOR}.${PATCH_VERSION}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4 : Afficher la version pour le débogage
      - name: Debug version
        run: echo "Calculated version: ${{ steps.version.outputs.version }}"

      # Étape 5 : Vérification de code (par exemple, linting ou tests légers)
      - name: Run lint
        run: echo "No build steps. Only linting and other checks."
